version: "3.5"

services:
  sento-db:
    container_name: sento-db
    image: geographica/postgis:spry_sparrow
    restart: unless-stopped
    volumes:
      - sento-data:/data
      - ./sento_api/database/init.sql:/src/init.sql:ro
    env_file: db.env
    networks:
      - sento-net

  sento-api:
    container_name: sento-api
    build:
      context: .
    networks:
      - sento-net

volumes:
  sento-data:
    external: true

networks:
  sento-net:
    name: sento-net
