"""Add sentiment to status

Revision ID: 893ca0e871a4
Revises: 2af73696b043
Create Date: 2019-03-23 12:26:15.167900+00:00

"""
from alembic import op
import sqlalchemy as sa

# flake8: noqa


# revision identifiers, used by Alembic.
revision = '893ca0e871a4'
down_revision = '2af73696b043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statuses', sa.Column('sentiment', sa.SmallInteger(), nullable=True), schema='data')
    op.create_index(op.f('ix_data_statuses_sentiment'), 'statuses', ['sentiment'], unique=False, schema='data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_statuses_sentiment'), table_name='statuses', schema='data')
    op.drop_column('statuses', 'sentiment', schema='data')
    # ### end Alembic commands ###
