"""Indices for topic id text search

Revision ID: 8e710859d57f
Revises: e5133ed08a8b
Create Date: 2019-05-10 16:11:14.153537+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e710859d57f'
down_revision = 'e5133ed08a8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_gist_data_rankings_topic_id', 'rankings', ['topic_id'], unique=False, schema='data', postgresql_using='gist', postgresql_ops={'topic_id': 'gist_trgm_ops'})
    op.create_index('ix_gist_data_statuses_topic_id', 'statuses', ['topic_id'], unique=False, schema='data', postgresql_using='gist', postgresql_ops={'topic_id': 'gist_trgm_ops'})
    op.create_index('ix_data_topics_id', 'topics', ['id'], unique=False, schema='data', postgresql_using='gist', postgresql_ops={'id': 'gist_trgm_ops'})
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_data_topics_id', table_name='topics', schema='data')
    op.drop_index('ix_gist_data_statuses_topic_id', table_name='statuses', schema='data')
    op.drop_index('ix_gist_data_rankings_topic_id', table_name='rankings', schema='data')
    # ### end Alembic commands ###
