"""empty message

Revision ID: aa9b9af5beba
Revises: 
Create Date: 2019-01-27 17:44:58.980768+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aa9b9af5beba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rankings',
    sa.Column('ranking_ts', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('ranking_no', sa.SmallInteger(), nullable=False),
    sa.Column('woeid', sa.Integer(), nullable=False),
    sa.Column('tweet_volume', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('ranking_ts', 'ranking_no', 'topic_id'),
    schema='data'
    )
    op.create_index(op.f('ix_data_rankings_ranking_ts'), 'rankings', ['ranking_ts'], unique=False, schema='data')
    op.create_index(op.f('ix_data_rankings_topic_id'), 'rankings', ['topic_id'], unique=False, schema='data')
    op.create_table('statuses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('wrote_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('fetched_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('topic_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='data'
    )
    op.create_index(op.f('ix_data_statuses_topic_id'), 'statuses', ['topic_id'], unique=False, schema='data')
    op.create_index(op.f('ix_data_statuses_wrote_at'), 'statuses', ['wrote_at'], unique=False, schema='data')
    op.create_table('topics',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('query_str', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='data'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topics', schema='data')
    op.drop_index(op.f('ix_data_statuses_wrote_at'), table_name='statuses', schema='data')
    op.drop_index(op.f('ix_data_statuses_topic_id'), table_name='statuses', schema='data')
    op.drop_table('statuses', schema='data')
    op.drop_index(op.f('ix_data_rankings_topic_id'), table_name='rankings', schema='data')
    op.drop_index(op.f('ix_data_rankings_ranking_ts'), table_name='rankings', schema='data')
    op.drop_table('rankings', schema='data')
    # ### end Alembic commands ###
