"""baseline

Revision ID: e2459aa6c178
Revises:
Create Date: 2019-02-12 21:45:45.729278+00:00

"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e2459aa6c178'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('the_geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, spatial_index=False), nullable=False),
    sa.Column('coords', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='data'
    )
    op.create_index('idx_locations_coords', 'locations', ['coords'], unique=False, schema='data', postgresql_using='gist')
    op.create_index('idx_locations_the_geom', 'locations', ['the_geom'], unique=False, schema='data', postgresql_using='gist')
    op.create_table('rankings',
    sa.Column('ranking_ts', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('ranking_no', sa.SmallInteger(), nullable=False),
    sa.Column('woeid', sa.Integer(), nullable=False),
    sa.Column('tweet_volume', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('ranking_ts', 'ranking_no', 'topic_id'),
    schema='data'
    )
    op.create_index(op.f('ix_data_rankings_woeid'), 'rankings', ['woeid'], unique=False, schema='data')
    op.create_table('statuses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('wrote_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('fetched_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('topic_id', sa.Text(), nullable=False),
    sa.Column('woeid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'topic_id', 'woeid'),
    schema='data'
    )
    op.create_index(op.f('ix_data_statuses_wrote_at'), 'statuses', ['wrote_at'], unique=False, schema='data')
    op.create_table('topics',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('query_str', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='data'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topics', schema='data')
    op.drop_index(op.f('ix_data_statuses_wrote_at'), table_name='statuses', schema='data')
    op.drop_table('statuses', schema='data')
    op.drop_index(op.f('ix_data_rankings_woeid'), table_name='rankings', schema='data')
    op.drop_table('rankings', schema='data')
    op.drop_index('idx_locations_the_geom', table_name='locations', schema='data')
    op.drop_index('idx_locations_coords', table_name='locations', schema='data')
    op.drop_table('locations', schema='data')
    # ### end Alembic commands ###
