"""Indices for rankings and statuses

Revision ID: e5133ed08a8b
Revises: 893ca0e871a4
Create Date: 2019-05-10 12:56:41.959798+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5133ed08a8b'
down_revision = '893ca0e871a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_data_rankings_ranking_no'), 'rankings', ['ranking_no'], unique=False, schema='data')
    op.create_index(op.f('ix_data_rankings_ranking_ts'), 'rankings', ['ranking_ts'], unique=False, schema='data')
    op.create_index(op.f('ix_data_rankings_topic_id'), 'rankings', ['topic_id'], unique=False, schema='data')
    op.create_index(op.f('ix_data_statuses_topic_id'), 'statuses', ['topic_id'], unique=False, schema='data')
    op.create_index(op.f('ix_data_statuses_woeid'), 'statuses', ['woeid'], unique=False, schema='data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_statuses_woeid'), table_name='statuses', schema='data')
    op.drop_index(op.f('ix_data_statuses_topic_id'), table_name='statuses', schema='data')
    op.drop_index(op.f('ix_data_rankings_topic_id'), table_name='rankings', schema='data')
    op.drop_index(op.f('ix_data_rankings_ranking_ts'), table_name='rankings', schema='data')
    op.drop_index(op.f('ix_data_rankings_ranking_no'), table_name='rankings', schema='data')
    # ### end Alembic commands ###
